import Sidebar from '@/components/layout/Sidebar'
import FollowBar from '@/components/layout/FollowBar'
import './globals.css'
import AppLayout from '@/components/layout/AppLayout'
import Modal from '@/components/Modal'
import LoginModal from '@/components/auth/LoginModal'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <LoginModal />
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  )
}
