import Sidebar from '@/components/layout/Sidebar'
import FollowBar from '@/components/layout/FollowBar'
import AppLayout from '@/components/layout/AppLayout'
import LoginModal from '@/components/auth/LoginModal'
import RegisterModal from '@/components/auth/RegisterModal'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <LoginModal />
        <RegisterModal />
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  )
}
